server:
  port: 8080
  forward-headers-strategy: framework

spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /index.html

jwt:
  secret: ${JWT_SECRET}
  validityMillis: ${JWT_VALIDITY_MILLIS:259200000}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    com.capitally: INFO
